name: Release Parcel.NET.Dhl.LocationFinder

on:
  push:
    tags: ['dhl-locationfinder/v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release-package.yml
    with:
      package: 'dhl-locationfinder'
      csproj-path: 'src/Parcel.NET.Dhl.LocationFinder/Parcel.NET.Dhl.LocationFinder.csproj'
      title-prefix: 'Parcel.NET.Dhl.LocationFinder'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
