name: Release Parcel.NET.Dhl.Internetmarke

on:
  push:
    tags: ['dhl-internetmarke/v*']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/release-package.yml
    with:
      package: 'dhl-internetmarke'
      csproj-path: 'src/Parcel.NET.Dhl.Internetmarke/Parcel.NET.Dhl.Internetmarke.csproj'
      title-prefix: 'Parcel.NET.Dhl.Internetmarke'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}
